---
- name: Sysctl module 
  hosts: all
  gather_facts: no
  become: true
  vars:
    sysctl_name: "vm.swappiness"
    sysctl_value: "0"
  tasks:
    - name: Set sysctl
      ansible.posix.sysctl:
        name: "{{ sysctl_name }}"
        value: "{{ sysctl_value }}"
        state: present
        sysctl_set: true
        reload: true

    - name: Disable IPv6 with sysctl
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: "present"
        reload: "yes"
      with_items:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

#    - name: Debian | blacklist ipv6 in modprobe
#      ansible.builtin.lineinfile:
#        dest: /etc/modprobe.d/blacklist.conf
#        line: 'blacklist ipv6'
#        mode: '0644'
#        create: yes
#      when: ansible_os_family == 'Debian'
    
    - package:
        name: sysfsutils
    - lineinfile:
        path: /etc/sysfs.conf
        line: kernel/mm/transparent_hugepage/enabled = never
#        state: absent
    - lineinfile:
        path: /etc/sysfs.conf
        line: kernel/mm/transparent_hugepage/defrag = never
#        state: absent
    
    - name: Display sysfs.conf contents
      command: cat sysfs.conf chdir=/etc
      register: command_output

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"
